development:
  adapter: postgresql
  encoding: unicode
  database: cafeteria_db
  username: postgres
  password: test
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: cafeteria_db_test
  username: postgres
  password: test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: cafeteria_db_prod
  username: postgres
  password: test
  host: localhost
  pool: 5
  timeout: 5000